### ISSUE TITLE
Force close on select alarm sound

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mathprocessing/kitchentimer#37]
```
What steps will reproduce the problem?
1.  Menu
2.  Preferences
3.  Check "Custom Alarm Sound"
4.  Touch "Select Alarm Sound"

What is the expected output? What do you see instead?

Expected:  A list of sounds to select or a file browser
Actual:  Force Close

Please include the following info:
Phone model?  Sanding Vibrant (Galaxy S on T-Mobile)
Android Version?  2.2
ROM?  Bionix-V 1.2.1

If possible, provide a logcat of the issue:
If you get a Force Close do an: adb logcat

Will for adv logcat at pc later.

Please provide any additional information below.

This is a fantastically good timer app and you made it free.  You are a true 
scholar and gentleman.


```

Original issue reported on code.google.com by `william....@gmail.com` on 21 Feb 2011 at 2:47

**Comment by GoogleCodeExporter** [comment]
```
Logcat attached.

I think this is the important part for the crash.  No idea why the 
RingtonePicker activity would crash.


I/ActivityManager( 2989): Starting activity: Intent { 
act=android.intent.action.RINGTONE_PICKER 
cmp=android/com.android.internal.app.RingtonePickerActivity (has extras) }
D/RingtoneManager( 8200): Internal SD : Environment.getExternalStorageState() 
return : mounted
E/ActivityThread( 8200): Failed to find provider info for drm
D/AndroidRuntime( 8200): Shutting down VM
W/dalvikvm( 8200): threadid=1: thread exiting with uncaught exception 
(group=0x4001d7d0)
E/AndroidRuntime( 8200): FATAL EXCEPTION: main
E/AndroidRuntime( 8200): java.lang.RuntimeException: Unable to start activity 
ComponentInfo{android/com.android.internal.app.RingtonePickerActivity}: 
java.lang.NullPointerException
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2663)
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2679)
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread.access$2300(ActivityThread.java:125)
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2033)
E/AndroidRuntime( 8200):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8200):    at android.os.Looper.loop(Looper.java:123)
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread.main(ActivityThread.java:4627)
E/AndroidRuntime( 8200):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 8200):    at java.lang.reflect.Method.invoke(Method.java:521)
E/AndroidRuntime( 8200):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
E/AndroidRuntime( 8200):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime( 8200):    at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 8200): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 8200):    at 
com.android.internal.app.RingtonePickerActivity.onPrepareListView(RingtonePicker
Activity.java:252)
E/AndroidRuntime( 8200):    at 
com.android.internal.app.AlertController$AlertParams.createListView(AlertControl
ler.java:909)
E/AndroidRuntime( 8200):    at 
com.android.internal.app.AlertController$AlertParams.apply(AlertController.java:
824)
E/AndroidRuntime( 8200):    at 
com.android.internal.app.AlertActivity.setupAlert(AlertActivity.java:73)
E/AndroidRuntime( 8200):    at 
com.android.internal.app.RingtonePickerActivity.onCreate(RingtonePickerActivity.
java:226)
E/AndroidRuntime( 8200):    at 
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
E/AndroidRuntime( 8200):    at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2627)
E/AndroidRuntime( 8200):    ... 11 more
W/ActivityManager( 2989):   Force finishing activity 
android/com.android.internal.app.RingtonePickerActivity
W/ActivityManager( 2989):   Force finishing activity 
com.leinardi.kitchentimer/.ui.ConfigActivity
I/        ( 2989): dumpmesg > /data/log/dumpstate_app_error.log
W/ActivityManager( 2989): Activity pause timeout for HistoryRecord{482b8dc0 
android/com.android.internal.app.RingtonePickerActivity}
W/PowerManagerService( 2989): Timer 0x7->0x3|0x0
I/PowerManagerService( 2989): Ulight 7->3|0
D/dalvikvm( 8156): GC_EXTERNAL_ALLOC freed 2967 objects / 438192 bytes in 50ms
V/MediaProvider( 3086): we got work to do for checkThumbnail: 
/mnt/sdcard/external_sd/Movie/avatar.dcf, there are still 1 tasks left in queue
D/MediaPlayerService( 2608): getPlayerType : url = 
/mnt/sdcard/external_sd/Movie/avatar.dcf, filePath = 
/mnt/sdcard/external_sd/Movie/avatar.dcf
D/MediaPlayerService( 2608): getPlayerType : filePath = 
/mnt/sdcard/external_sd/Movie/avatar.dcf
V/WindowManager( 2989): Dsptch > Window{483b5778 Sorry! paused=false}
V/InputDevice( 2989): ID[0]=0(0) Dn(0=>1)
I/PowerManagerService( 2989): Ulight 3->7|0
D/MediaPlayerService( 2608): getPlayerType : pContentInfo->szMimeType = 
video/3gpp
D/MediaPlayerService( 2608): getPlayerType : It's not an OMADRM-Midi file.
E/MetadataDriver( 2608): MetadataDriver::setDataSource url file type is 
isAudiofile(0)
V/WindowManager( 2989): Dsptch > Window{483b5778 Sorry! paused=false}
V/InputDevice( 2989): ID[0]=0(0) Up(1=>0)
I/Process ( 8200): Sending signal. PID: 8200 SIG: 9
E/JavaBinder( 2989): !!! FAILED BINDER TRANSACTION !!!
I/ActivityManager( 2989): Process com.leinardi.kitchentimer (pid 8200) has died.
I/WindowManager( 2989): WIN DEATH: Window{48767328 
com.leinardi.kitchentimer/com.leinardi.kitchentimer.ui.MainActivity 
paused=false}
I/WindowManager( 2989): WIN DEATH: Window{483934b0 
com.leinardi.kitchentimer/com.leinardi.kitchentimer.ui.ConfigActivity 
paused=false}
I/UsageStats( 2989): Unexpected resume of com.ebproductions.android.launcher 
while already resumed in com.leinardi.kitchentimer
```

Original comment by `william....@gmail.com` on 21 Feb 2011 at 8:19

Attachments:
- [logcat.txt](https://storage.googleapis.com/google-code-attachments/kitchentimer/issue-37/comment-1/logcat.txt)

**Comment by GoogleCodeExporter** [comment]
```
Very strange, do you have some other problem with the alarm ringtones?

Could you try to copy some audio files (.wav, .ogg, .mp3) in the following path?
/sdcard/media/audio/alarms/
```

Original comment by `leinardi` on 24 Feb 2011 at 12:19
- Added labels: **OpSys-Custom**

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem. 

Samsung SGH-I997 (Infuse)
Version 2.3.6
Build number: GINGERBREAD.UCLB3
ROM: No ROM.
```

Original comment by `christop...@gmail.com` on 12 Nov 2012 at 11:20
